###
## This is the place to override the wordpress cookbook's default attributes.
##
## Do not edit THIS file directly. Instead, create
## "wordpress/attributes/customize.rb" in your cookbook repository and
## put the overrides in YOUR customize.rb file.
####
#
## The following shows how to override the wordpress enable_W3TC used:
##
#normal[:wordpress][:wp_config][:enable_W3TC] = false
